//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoHiem
    {
        public string MaBaoHiem { get; set; }
        public string LoaiBaoHiem { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string ChiTietBaoHiem { get; set; }
        public string MaNhanVien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
