//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuCap
    {
        public string MaPhuCap { get; set; }
        public string MaLuong { get; set; }
        public string LoaiPhuCap { get; set; }
        public Nullable<decimal> SoTien { get; set; }
    
        public virtual Luong Luong { get; set; }
    }
}
