//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagement.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public string MaHopDong { get; set; }
        public string LoaiHopDong { get; set; }
        public Nullable<System.DateTime> NgayBatDauHopDong { get; set; }
        public Nullable<System.DateTime> NgayKetThucHopDong { get; set; }
        public string ChiTietHopDong { get; set; }
        public string MaNhanVien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
