//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagement.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        public string MaLamViec { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayLamViec { get; set; }
        public Nullable<int> SoGioLamViec { get; set; }
        public Nullable<int> SoGioLamThem { get; set; }
        public string TrangThai { get; set; }
        public string ChuThich { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
